name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization Environment
        run: |
          sudo apt update -y
          sudo apt install -y upx-ucl libfuse-dev

      - name: Update Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Custom Config
        run: |
          cat > .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-openclash=y
          EOF

      - name: Download Dependencies
        run: make download -j$(nproc)

      - name: Compile Firmware
        run: make -j$(nproc) || make -j1 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: bin/targets/*/*
